### ISSUE TITLE
How to use broker url here?

### ISSUE THREAD

**Issue by uncannyMBM** [asseco-voice/laravel-stomp#25]

**Comment by Norgul** [comment]
Did you check out readme?

**Comment by uncannyMBM** [comment]
I did check that. Actually I didn't get understand. I wan't connect a 3rd party host. They will provide some events and I need to catch it. Can you help me out? I'll be thankful to you.

Here is the details of connection? How to connect with these data?

{
    "url": "wss://use1-central-webstomp.hs1api.com/ws",
    "virtual-host": "central",
    "user": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJxdWV1ZXMiOlsiXmFwaUNvbnN1bWVyc1xcLjM5YjRjZDcxLTRkMTMtNGMzZi1iZGY4LTIyNjUzOGQ5OTk0ZVxcLi4rJCJdLCJyb3V0ZUtleXMiOlsiXlteXFwuXStcXC5bXlxcLl0rXFwuW15cXC5dK1xcLlteXFwuXSskIl0sInNjb3BlIjpbInN0cmVhbS1hcGk6cmVhZCJdLCJleGNoYW5nZXMiOlsiXmFwaUNvbnN1bWVyc1xcLjM5YjRjZDcxLTRkMTMtNGMzZi1iZGY4LTIyNjUzOGQ5OTk0ZSJdLCJleHAiOjE2NjI5Mjg0NDEsImlhdCI6MTY1OTMyODQ0MSwianRpIjoiNTI5YjQ4MTgtMGIzMi00ZWI0LTgyOTQtZTliZDJiMzE1YTAwIn0.mp-1vOMRMZpKjCetl9rg7ZsiqpSMkz7sKZfQEGMcudP2HiTkWADvnlsNX1QjwFICALqteWpYnXBpbNp0C7aZG1yy5gAU_ngQmY3E2MaYBDC93P5hE42THymGyQ49zCpecP3picOinB6urjWk6FBGFarlMwzAC-RmOHOb6O-2hDzNsez1oIix3nKMx_UJgWsmwl5cCjMY9REAzzKR9bOvOASCuUhKUu8DXK1bznP5SliGaiSWz1Ny6bq_dPPjyfhIwZZuDkUg29lwXfp09Em-679btYCdh_x7pwOECdeNBWnLtcZNUYR8RBHAIjGF-svgCGLjeDd5VHtKIWla3JEOGPoM4eV4QY6N5xXS9x_dIozhkahLPyHtIseZrVGRBFDRtrvgFacbWCFfSQ_HLAzVy-EI70dNoCvB3SCW6ZBWSOpoPmkVlWk2rA4d_9WKgG1_Fg5s2tIrr3QjISmdrGNZwWnStOUwa7Im-Obsuz7aO16uaqVf5hpIeSZ8pPWfCF1qmYfhnjXwLxZmZF2tXXfIGwESQCeCzh5Y-cASonhDmzOhzG0QJKNojdsdZEMP4g_q76QMWb56Ru9262EFSEjlsmpgn9HXfOoqFskw94ayPVz3qvDwc-2uFHiwsQO3q1DewVQGyjwsARXSw_CE-E5Rtkdv2Tyqr-5KT5beOoWvbh0",
    "exchanges": "apiConsumers.39b4cd71-4d13-4c3f-bdf8-226538d9994e",
    "queues": "apiConsumers.39b4cd71-4d13-4c3f-bdf8-226538d9994e",
    "routingKeys": "*.*.*.*"
}
